design: Header UI 구현
sos-sejong-opensource-software/seggle-frontend pull request #4
Opened 2023-01-09 10:47 UTC by judahhh

구현 기능
-Header UI 구현

2023-01-10 14:16 UTC, minkyung00 requested changes

2023-01-10 14:16 UTC, minkyung00 commented on src/components/molecules/Header.tsx
> +const Header = () => {
노션에 있는 [컴포넌트 컨벤션](https://www.notion.so/sejong-sos/80874665b5514293a940ffc4808557a7) 에 맞춰서 수정 부탁드립니다!

2023-01-10 14:16 UTC, minkyung00 commented on src/components/molecules/Header.tsx
> +              </Link>
이 부분도 컴포넌트로 분리해보는건 어떨까요?

아래 수업 / 건의게시판 / 공지사항 / FAQ 와 중복되기 때문에 분리해도 좋을 것 같습니다~

2023-01-10 14:16 UTC, minkyung00 commented on src/App.tsx
> +//import { FC } from 'react';
주석은 지우고 올려주세요!

2023-01-10 14:16 UTC, minkyung00 commented on src/App.tsx
> +import Faq from './components/pages/Faq';
[폴더구조를 노션](https://www.notion.so/sejong-sos/220102-006bd6a6942542edb42622149d82907e)으로만 전달해서 제대로 확인을 못하신 것 같아요!

pages 폴더는 src 폴더 바로 하위 폴더로, src/pages로 해주시면 됩니다!

2023-01-10 14:22 UTC, minkyung00 commented
다현님 수고하셨습니다~~~👍

### 참고사항
- PR은 main이 아니라 dev 브랜치로 날려주시면 됩니다! (이번 PR은 제가 수정했습니다!)
- UI 관련 PR이라면 스크린샷도 함께 추가해주시면 👍👍👍

### 제안사항
- merge 충돌난 파일들 수정해서 반영 부탁드립니다!
- 리뷰 내용 중 이해가 안가거나 더 좋은 의견 있으면 편하게 말해주세요!

2023-01-12 10:28 UTC, judahhh commented
흑흑 리액트 너무 어렵습니다,,, 확인해볼게요!!

2023-01-13 05:07 UTC, inyeong-kang commented
고생하셨어요 다현 님!!

2023-01-13 15:33 UTC, minkyung00 approved these changes

2023-01-25 11:46 UTC, merged